- hosts: web

  vars_files:
    - variable.yml

  tasks:

  - name: install apache and php last version
    yum:
      name:
        - httpd
        - php
        - php-mysql
      state: present
      update_cache: yes

  - name: Give writable mode to http folder
    file:
      path: /var/www/html
      state: directory
      mode: '0755'

  - name: remove default index.html
    file:
      path: /var/www/html/index.html
      state: absent

  - name: upload web app source
    copy:
      src: /app/
      dest: /var/www/html/

  - name: deploy php database config
    template:
      src: "db-config.php.j2"
      dest: "/var/www/html/db-config.php"

  - name: ensure apache service is start
    service:
      name: httpd
      state: started
      enabled: yes

  - name: "Restart apache"
    systemd:
      name: httpd
      state: restarted
      enabled: yes

- hosts: web
  become: true
  vars_files:
    - variable.yml



- name: Déploiement Apache
  hosts: web
  roles:
    - apache

- name: Deploiement mariadb
  hosts: web
  roles: 
    - createuser

